version: '3'
services:
  frontend:
    build: ./frontend/
    ports:
      - 3000:3000
    volumes:
      - ./frontend/:/usr/app/
      - /usr/app/node_modules
  backend:
    build: ./backend/
    ports:
      - 3003:3003
    volumes:
      - ./backend/:/usr/app/
      - /usr/app/node_modules
