version: '3'
services:
  frontend:
    build: ./frontend/
    ports:
      - 3000:3000
    depends_on:
      - backend
  backend:
    build: ./backend/
    volumes:
      - ./backend/:/usr/app/
    ports:
      - 3003:3003
